[@ww.select cssClass="builderSelectWidget" labelKey='blazemeter.test' name='selectedtest' list='testlist' required='true' emptyOption='false'/]
[@ww.textfield labelKey="blazemeter.config.jmeterProps" name="jmeter.properties" required='false'/]
[@ww.textarea labelKey="blazemeter.config.notes" name="notes" required='false'/]
[@ww.checkbox labelKey="blazemeter.config.jtl" name='jtl.report' toggle='true' description=''/]
[@ww.checkbox labelKey="blazemeter.config.junit" name='junit.report' toggle='true' description=''/]